# Generated by Django 5.0.3 on 2024-03-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db',
            name='age',
        ),
        migrations.AddField(
            model_name='db',
            name='gg',
            field=models.BooleanField(default=True),
        ),
    ]
